#Square tiles
LIGHT_SQUARE_COLOR = (240, 217, 181) #Light Brown
DARK_SQUARE_COLOR = (181, 136, 99) #Dark Brown
TILE_SIZE = 100
ROWS_ITER = COLS_ITER = range(0, 8)

#MARGINS
MARGIN_WIDTH = 20
MARGIN_BG_COLOR = (102, 51, 45) #Mahogany
MARGIN_HEADER_COLOR = (255, 255, 255) #White
MARGIN_FONT_STYLE = None
MARGIN_FONT_SIZE = 24

#Display window
BOARD_SIZE = 8 * TILE_SIZE
WINDOW_SIZE = BOARD_SIZE + 2 * MARGIN_WIDTH
WINDOW_DIM = (WINDOW_SIZE, WINDOW_SIZE)
WINDOW_CENTER = (WINDOW_SIZE/2, WINDOW_SIZE/2)
WINDOW_TITLE = "Magdalene Chess Engine"